### ISSUE TITLE
Using google.maps.event.addListener manually with ui-map directive

### ISSUE THREAD

**Issue by bennlich** [angular-ui/angular-ui-OLDREPO#235]
If you use the ui-map directive, are you required to bind events through the ui-event directive? I tried binding events manually with google.maps.event.addListener and got some strange errors. The only reason I tried to do it manually was so that I didn't have to deal with $apply.

TypeError: Cannot read property '__e3_' of null
    at af (http://maps.gstatic.com/intl/en_us/mapfiles/api-3/9/17/main.js:18:949)
    at new Ze (http://maps.gstatic.com/intl/en_us/mapfiles/api-3/9/17/main.js:21:320)
    at Object.Q.addListener (http://maps.gstatic.com/intl/en_us/mapfiles/api-3/9/17/main.js:18:667)
    at Object.init (http://localhost/~bennlich/ckapps/js/services.js:328:21)
    at new MapCtrl (http://localhost/~bennlich/ckapps/js/controllers.js:140:13)
    at invoke (http://localhost/~bennlich/ckapps/lib/angular-1.0.2.js:2795:28)
    at Object.instantiate (http://localhost/~bennlich/ckapps/lib/angular-1.0.2.js:2805:23)
    at http://localhost/~bennlich/ckapps/lib/angular-1.0.2.js:4621:24
    at update (http://localhost/~bennlich/ckapps/lib/angular-1.0.2.js:13762:26)
    at http://localhost/~bennlich/ckapps/lib/angular-1.0.2.js:8040:24

**Comment by ajoslin** [comment]
Using ui-event is 'better' because it follows the angular way: Binding DOM events in the view, not in your controller.

But you should still be able to do it, eg:

``` javascript
google.maps.event.addListener($scope.myMap, "click", function() { /*stuff*/ });
```

Make sure you do it after the map is initialized, though.

**Comment by bennlich** [comment]
Ah, okay. I'm setting up the events in a service, which isn't too bad I don't think. I guess still not as 'good' as binding in the view. I get tons of non-fatal $apply errors when I setup events in a ui-event directive though.
