### ISSUE TITLE
ui.date - TypeError: Object [object Object] has no method 'datepicker'

### ISSUE THREAD

**Issue by tedx** [angular-ui/angular-ui-OLDREPO#562]
I've used bower to install angular-ui-date and I have a jade file that contains:

```
  input(ui-date="{ dateFormat: 'yy-mm-dd' }", ui-date-format, ng-model="contact.date")
```

When I run the app I see in the JavaScript console the following error repeated twice.

TypeError: Object [object Object] has no method 'datepicker'
    at Object.initDateWidget [as fn](http://localhost:3000/components/angular-ui-date/src/date.js:71:17)
    at Object.e.$digest (http://localhost:3000/components/angular/angular.min.js:86:409)
    at Object.e.$apply (http://localhost:3000/components/angular/angular.min.js:88:506)
    at e (http://localhost:3000/components/angular/angular.min.js:95:38)
    at p (http://localhost:3000/components/angular/angular.min.js:98:123)
    at XMLHttpRequest.t.onreadystatechange (http://localhost:3000/components/angular/angular.min.js:99:259)

Is there any order dependency for script includes? I'm using:
  script(src="components/jquery/jquery.min.js")
  script(src='components/angular/angular.min.js')
  script(src="components/angular-ui-date/src/date.js")

Can anyone help me to understand what the problem is?

Thanks
Ted

**Comment by ProLoser** [comment]
Sounds like you forgot to load the jquery-ui datepicker .js file.

This specific plugin has been relocated to angular-ui/ui-date

**Comment by tedx** [comment]
that did the trick thanks.

Ted

**Comment by archanasv** [comment]
we need to install manually or will it work if i include as directive. anyone please help me
